/*
 JUST A REMINDER, WHEN COMMITING NEW WORK, ONLY CHOOSE THE PACKAGE YOUR WORKING IN, NOT THE MASTER PACKAGE, AS THIS COULD OVERWRITE THE WHOLE
PROJECT IF PEOPLE ARE DOING IT SIMULTANEOUSLY.
 */
package GUI;

/**
 *
 * @author Matthew
 */
public class GUI {
    
}
